version: '3.8'
services:
  #sonarr
  sonarr:
    container_name: sonarr
    restart: unless-stopped
    ports:
      - '8989:8989'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=NZ
    volumes:
      - '/mnt/c/dev/servarr/sonarr/config:/config'
      - '/mnt/x:/data'
      - '/mnt/y:/data-y'
      - '/mnt/z:/data-z'
    image: ghcr.io/hotio/sonarr
